import { describe, it, expect, beforeEach, afterEach } from "vitest";
import { resolve } from "node:path";
import { mkdtemp, rm, readFile, readdir } from "node:fs/promises";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { convertTitle } from "./converter.js";
import type { ConvertOptions } from "./converter.js";

const FIXTURES_DIR = resolve(import.meta.dirname, "../../../fixtures/fragments");

/** Default options for tests */
const DEFAULTS: Omit<ConvertOptions, "input" | "output"> = {
  granularity: "section",
  linkStyle: "plaintext",
  includeSourceCredits: true,
  includeNotes: true,
  includeEditorialNotes: false,
  includeStatutoryNotes: false,
  includeAmendments: false,
  dryRun: false,
};

describe("convertTitle", () => {
  let outputDir: string;

  beforeEach(async () => {
    outputDir = await mkdtemp(join(tmpdir(), "lexbuild-test-"));
  });

  afterEach(async () => {
    await rm(outputDir, { recursive: true, force: true });
  });

  it("converts simple-section.xml and writes one section file", async () => {
    const result = await convertTitle({
      ...DEFAULTS,
      input: resolve(FIXTURES_DIR, "simple-section.xml"),
      output: outputDir,
    });

    expect(result.sectionsWritten).toBe(1);
    expect(result.titleNumber).toBe("1");
    expect(result.titleName).toBe("GENERAL PROVISIONS");
    expect(result.files).toHaveLength(1);

    // Check the output file exists at the right path
    const expectedPath = join(outputDir, "usc", "title-01", "chapter-01", "section-2.md");
    expect(result.files[0]).toBe(expectedPath);

    // Read and verify content
    const content = await readFile(expectedPath, "utf-8");

    // Should have frontmatter
    expect(content).toMatch(/^---\n/);
    expect(content).toContain("identifier");
    expect(content).toContain("/us/usc/t1/s2");

    // Should have section heading
    expect(content).toContain("# § 2.");
    expect(content).toContain("County");

    // Should have content text
    expect(content).toContain("county");
    expect(content).toContain("parish");

    // Should have source credit
    expect(content).toContain("**Source Credit**");
  });

  it("converts section-with-subsections.xml", async () => {
    const result = await convertTitle({
      ...DEFAULTS,
      input: resolve(FIXTURES_DIR, "section-with-subsections.xml"),
      output: outputDir,
    });

    expect(result.sectionsWritten).toBe(1);
    expect(result.files).toHaveLength(1);

    const content = await readFile(result.files[0]!, "utf-8");

    // Should have subsection numbering
    expect(content).toContain("**(a)**");
    expect(content).toContain("**(b)**");
    expect(content).toContain("**(c)**");

    // Should have source credit
    expect(content).toContain("**Source Credit**");
  });

  it("creates correct directory structure", async () => {
    await convertTitle({
      ...DEFAULTS,
      input: resolve(FIXTURES_DIR, "simple-section.xml"),
      output: outputDir,
    });

    // Check directory structure
    const uscDir = join(outputDir, "usc");
    const titleDir = join(uscDir, "title-01");
    const chapterDir = join(titleDir, "chapter-01");

    const titleContents = await readdir(titleDir);
    expect(titleContents).toContain("chapter-01");

    const chapterContents = await readdir(chapterDir);
    expect(chapterContents).toContain("section-2.md");
  });

  it("generates title-level README.md with chapter listing", async () => {
    await convertTitle({
      ...DEFAULTS,
      input: resolve(FIXTURES_DIR, "simple-section.xml"),
      output: outputDir,
    });

    const readmePath = join(outputDir, "usc", "title-01", "README.md");
    const readme = await readFile(readmePath, "utf-8");

    // Should have title heading
    expect(readme).toContain("# Title 1 — GENERAL PROVISIONS");

    // Should have stats table
    expect(readme).toContain("**Positive Law**");
    expect(readme).toContain("Yes");
    expect(readme).toContain("**Sections**");
    expect(readme).toContain("**Chapters**");

    // Should have chapter listing
    expect(readme).toContain("## Chapters");
    expect(readme).toContain("### Chapter 1 — RULES OF CONSTRUCTION");
    expect(readme).toContain("1 section");
    expect(readme).toContain("chapter-01/");

    // Should have footer
    expect(readme).toContain("Generated by");
  });

  it("generates valid YAML frontmatter with correct fields", async () => {
    const result = await convertTitle({
      ...DEFAULTS,
      input: resolve(FIXTURES_DIR, "simple-section.xml"),
      output: outputDir,
    });

    const content = await readFile(result.files[0]!, "utf-8");

    // Extract frontmatter
    const fmMatch = /^---\n([\s\S]*?)\n---/.exec(content);
    expect(fmMatch).not.toBeNull();

    const fmText = fmMatch![1]!;
    expect(fmText).toContain("title_number: 1");
    expect(fmText).toContain('section_number: "2"');
    expect(fmText).toContain("positive_law: true");
    expect(fmText).toContain("chapter_number: 1");
  });

  it("strips source credits when includeSourceCredits is false", async () => {
    const result = await convertTitle({
      ...DEFAULTS,
      input: resolve(FIXTURES_DIR, "simple-section.xml"),
      output: outputDir,
      includeSourceCredits: false,
    });

    const content = await readFile(result.files[0]!, "utf-8");
    expect(content).not.toContain("**Source Credit**");
  });

  it("excludes all notes when includeNotes is false", async () => {
    const result = await convertTitle({
      ...DEFAULTS,
      input: resolve(FIXTURES_DIR, "section-with-notes.xml"),
      output: outputDir,
      includeNotes: false,
    });

    const content = await readFile(result.files[0]!, "utf-8");
    // Should not contain note headings
    expect(content).not.toContain("## Editorial Notes");
    expect(content).not.toContain("### Amendments");
    expect(content).not.toContain("### Severability");
    // Should still contain section content and source credit
    expect(content).toContain("**(a)**");
    expect(content).toContain("**Source Credit**");
  });

  it("includes only amendments when includeAmendments is set", async () => {
    const result = await convertTitle({
      ...DEFAULTS,
      input: resolve(FIXTURES_DIR, "section-with-notes.xml"),
      output: outputDir,
      includeNotes: false,
      includeAmendments: true,
    });

    const content = await readFile(result.files[0]!, "utf-8");
    // Should contain editorial cross-heading and amendments
    expect(content).toContain("## Editorial Notes");
    expect(content).toContain("### Amendments");
    // Should not contain statutory notes
    expect(content).not.toContain("### Severability");
    expect(content).not.toContain("### Findings");
  });

  it("includes only statutory notes when includeStatutoryNotes is set", async () => {
    const result = await convertTitle({
      ...DEFAULTS,
      input: resolve(FIXTURES_DIR, "section-with-notes.xml"),
      output: outputDir,
      includeNotes: false,
      includeStatutoryNotes: true,
    });

    const content = await readFile(result.files[0]!, "utf-8");
    // Should contain statutory notes
    expect(content).toContain("## Statutory Notes");
    expect(content).toContain("### Severability");
    expect(content).toContain("### Findings");
    // Should not contain editorial/amendment notes
    expect(content).not.toContain("### Amendments");
  });

  it("outputs chapter-level files when granularity is chapter", async () => {
    const result = await convertTitle({
      ...DEFAULTS,
      input: resolve(FIXTURES_DIR, "simple-section.xml"),
      output: outputDir,
      granularity: "chapter",
    });

    expect(result.sectionsWritten).toBeGreaterThan(0);
    expect(result.files).toHaveLength(1);

    // Should be a chapter file, not a section file in a subdirectory
    const filePath = result.files[0]!;
    expect(filePath).toContain("chapter-01.md");
    expect(filePath).not.toContain("chapter-01/");

    // Content should have chapter heading and section as H2
    const content = await readFile(filePath, "utf-8");
    expect(content).toContain("# Chapter 1");
    expect(content).toContain("## § 2.");
  });

  it("reports structure without writing files in dry-run mode", async () => {
    const result = await convertTitle({
      ...DEFAULTS,
      input: resolve(FIXTURES_DIR, "simple-section.xml"),
      output: outputDir,
      dryRun: true,
    });

    expect(result.dryRun).toBe(true);
    expect(result.sectionsWritten).toBe(1);
    expect(result.chapterCount).toBe(1);
    expect(result.totalTokenEstimate).toBeGreaterThan(0);
    // No files should be written
    expect(result.files).toHaveLength(0);

    // Verify output directory is empty
    const { readdir } = await import("node:fs/promises");
    await expect(readdir(join(outputDir, "usc"))).rejects.toThrow();
  });

  describe("duplicate section handling", () => {
    it("disambiguates duplicate section numbers with -2 suffix", async () => {
      const result = await convertTitle({
        ...DEFAULTS,
        input: resolve(FIXTURES_DIR, "duplicate-sections.xml"),
        output: outputDir,
      });

      // Should produce 3 files: section-3598.md, section-3598-2.md, section-3599.md
      expect(result.sectionsWritten).toBe(3);
      expect(result.files).toHaveLength(3);

      const chapterDir = join(outputDir, "usc", "title-05", "chapter-35");
      const files = await readdir(chapterDir);
      expect(files).toContain("section-3598.md");
      expect(files).toContain("section-3598-2.md");
      expect(files).toContain("section-3599.md");
    });

    it("writes distinct content to each duplicate file", async () => {
      await convertTitle({
        ...DEFAULTS,
        input: resolve(FIXTURES_DIR, "duplicate-sections.xml"),
        output: outputDir,
      });

      const chapterDir = join(outputDir, "usc", "title-05", "chapter-35");
      const first = await readFile(join(chapterDir, "section-3598.md"), "utf-8");
      const second = await readFile(join(chapterDir, "section-3598-2.md"), "utf-8");

      expect(first).toContain("first version");
      expect(second).toContain("second version");
      expect(first).not.toContain("second version");
      expect(second).not.toContain("first version");
    });

    it("lists both duplicates in _meta.json", async () => {
      await convertTitle({
        ...DEFAULTS,
        input: resolve(FIXTURES_DIR, "duplicate-sections.xml"),
        output: outputDir,
      });

      const metaPath = join(outputDir, "usc", "title-05", "chapter-35", "_meta.json");
      const meta = JSON.parse(await readFile(metaPath, "utf-8")) as {
        sections: Array<{ number: string; file: string }>;
      };

      const s3598files = meta.sections.filter((s) => s.number === "3598").map((s) => s.file);
      expect(s3598files).toHaveLength(2);
      expect(s3598files).toContain("section-3598.md");
      expect(s3598files).toContain("section-3598-2.md");
    });
  });

  describe("title granularity", () => {
    it("outputs title-level file when granularity is title", async () => {
      const result = await convertTitle({
        ...DEFAULTS,
        input: resolve(FIXTURES_DIR, "simple-section.xml"),
        output: outputDir,
        granularity: "title",
      });

      expect(result.sectionsWritten).toBeGreaterThan(0);
      expect(result.files).toHaveLength(1);

      const filePath = result.files[0]!;
      expect(filePath).toContain("title-01.md");
      expect(filePath).not.toContain("title-01/");

      const content = await readFile(filePath, "utf-8");
      expect(content).toContain("# Title 1");
      expect(content).toContain("## CHAPTER 1");
      // Section should be H3 (one level below the H2 chapter), not H4
      expect(content).toMatch(/^### §/m);
      expect(content).not.toMatch(/^#### §/m);
    });

    it("does not create _meta.json or README.md for title granularity", async () => {
      await convertTitle({
        ...DEFAULTS,
        input: resolve(FIXTURES_DIR, "simple-section.xml"),
        output: outputDir,
        granularity: "title",
      });

      // Should not have title subdirectory at all
      const uscDir = join(outputDir, "usc");
      const contents = await readdir(uscDir);
      expect(contents).toEqual(["title-01.md"]);
    });

    it("includes enriched frontmatter fields for title granularity", async () => {
      const result = await convertTitle({
        ...DEFAULTS,
        input: resolve(FIXTURES_DIR, "simple-section.xml"),
        output: outputDir,
        granularity: "title",
      });

      const content = await readFile(result.files[0]!, "utf-8");
      const fmMatch = /^---\n([\s\S]*?)\n---/.exec(content);
      expect(fmMatch).not.toBeNull();

      const fmText = fmMatch![1]!;
      expect(fmText).toContain("chapter_count:");
      expect(fmText).toContain("section_count:");
      expect(fmText).toContain("total_token_estimate:");
    });

    it("reports correct stats in dry-run mode for title granularity", async () => {
      const result = await convertTitle({
        ...DEFAULTS,
        input: resolve(FIXTURES_DIR, "simple-section.xml"),
        output: outputDir,
        granularity: "title",
        dryRun: true,
      });

      expect(result.dryRun).toBe(true);
      expect(result.sectionsWritten).toBe(1);
      expect(result.chapterCount).toBe(1);
      expect(result.totalTokenEstimate).toBeGreaterThan(0);
      expect(result.files).toHaveLength(0);
    });
  });

  describe("status handling", () => {
    it("includes status in frontmatter for sections with status", async () => {
      const result = await convertTitle({
        ...DEFAULTS,
        input: resolve(FIXTURES_DIR, "section-with-status.xml"),
        output: outputDir,
      });

      expect(result.sectionsWritten).toBe(4);

      const chapterDir = join(outputDir, "usc", "title-05", "chapter-10");

      // Repealed section should have status in frontmatter
      const repealed = await readFile(join(chapterDir, "section-1001.md"), "utf-8");
      expect(repealed).toContain('status: "repealed"');

      // Transferred section
      const transferred = await readFile(join(chapterDir, "section-1002.md"), "utf-8");
      expect(transferred).toContain('status: "transferred"');

      // Reserved section
      const reserved = await readFile(join(chapterDir, "section-1003.md"), "utf-8");
      expect(reserved).toContain('status: "reserved"');

      // Normal section should NOT have status field (omitted when current)
      const normal = await readFile(join(chapterDir, "section-1004.md"), "utf-8");
      expect(normal).not.toContain("status:");
    });

    it("includes status in _meta.json for all sections", async () => {
      await convertTitle({
        ...DEFAULTS,
        input: resolve(FIXTURES_DIR, "section-with-status.xml"),
        output: outputDir,
      });

      const metaPath = join(outputDir, "usc", "title-05", "chapter-10", "_meta.json");
      const meta = JSON.parse(await readFile(metaPath, "utf-8")) as {
        sections: Array<{ number: string; status: string }>;
      };

      const byNumber = Object.fromEntries(meta.sections.map((s) => [s.number, s.status]));
      expect(byNumber["1001"]).toBe("repealed");
      expect(byNumber["1002"]).toBe("transferred");
      expect(byNumber["1003"]).toBe("reserved");
      expect(byNumber["1004"]).toBe("current");
    });
  });
});
